### ISSUE TITLE
docker.client.compose appears to be broken in develop

### ISSUE THREAD

**Issue by nembery** [salt-formulas/salt-formula-docker#10]
Currently, using the example pillar for client.compose while using the develop branch is broken. The issue appears to be that lines 54 and 55 in compose.sls do not output valid yaml due to the recent change to unicode in salt. 

This issue seems to be the culprit:
https://github.com/saltstack/salt/issues/37692 

This patch https://github.com/saltstack/salt/pull/38554/commits/f7712d417f15d4b20144003cc379158ec0394f83 would apparently fix this issue, however, it is not yet present in the develop branch.

**Comment by fpytloun** [comment]
Hello,
thank you for bug report.
It seems that it's purely bug in development version of saltstack and that we cannot do much about it.

**Comment by nembery** [comment]
Closing now to de-clutter your issues. Thanks
